#Max likelihood for laterality models
#by DVM Bishop, 26th October 2017
#Updated 8th Nov 2017
#Updated 22nd Nov 2017 to include modeling of means

#Needs OpenMx, which you get with following command (not CRAN)
#source('http://openmx.psyc.virginia.edu/getOpenMx.R')
#
require(OpenMx)
library(DiagrammeR) #for the diagram
##########################################################################
#Early versions of script checked impact of subjects doing just a subset of the tasks
#With final bifactor model, this does not converge, so this is just of historical interest
#and we will run this with ntasks and donetasks both equal to 6

#Check how many combinations of possible tasks 
ntasks<-6 #N tasks
x<-1:ntasks 
donetasks<-6
allcombo<-combn(x, donetasks, FUN = NULL) #To see all combinations
ncombo<-ncol(allcombo) #this is only interesting if donetasks < Ntasks!
tasksubset<-0
if(donetasks<ntasks){tasksubset<-1}
##########################################################################
#Small matrix to hold p-values for comparative fits
psummary<-matrix(rep(NA,8),nrow=2)
rownames(psummary)<-c('Data from 1factor','Data from 2factor')
colnames(psummary)<-c('N','p.2fac_better.05','p.2fac_better.025','p.2fac_better.01')

##########################################################################
for (myfactor in 1:2) { #run sequentially with dataset generated by 1 or 2 factor model
  #read in big file of simulated data from 1 or 2 factor case
  #NB err0.35 refers to error term added to weighting - so far simulations have used this value but could change
  myrawfile<-paste0('Factor',myfactor,'_ABCDEFx2_meandiff_err0.35_raw.csv')
  alltask<-read.csv(myrawfile)
  alltask<-alltask[,13:24] #this selects the transformed scores that give bimodal distribution
  #for untransformed specify columns 1:12
  
  bigN<-nrow(alltask)
  myN<-30 #specify here the sample size to be used
  nrun<-120 #N runs of simulation
  #NB for pre-registration doc, we did 10,000 runs to get out pvalues
  
  mylabels<-c('A1','B1','C1','D1','E1','F1','A2','B2','C2','D2','E2','F2')
  colnames(alltask)<-mylabels
  ##########################################################################
  #Set up matrix to hold results of model testing
  myresults<-data.frame(matrix(rep(NA,nrun*20),nrow=nrun) )
  colnames(myresults)<-c('Factors','N','Sat.-2LL','Sat.df','Sat.BIC',
                         'Fac1.-2LL','Fac1.df','Fac1.BIC','Fac1.rmsea','Fac1.cfi','Fac1.tli',
                         'Fac2.-2LL','Fac2.df','Fac2.BIC','Fac2.rmsea','Fac2.cfi','Fac2.tli',
                         'F1-F2.-2LL','F1-F2.df','F1-F2.p')
 
  #-------------------------------------------------------------------------
  #Start loop here for repeated sampling and model testing

  for (j in 1:nrun)
  {
    #Now sample myN cases from the population
    my_raw<-alltask[sample(bigN,myN),]
    
    # Looked at effect of using ranks instead of raw scores: model v unhappy!
    # if(useranks==1){
    # my_rank<-matrix(rank(my_raw),ncol=12)
    # my_raw<-data.frame(my_rank)
    # }
    # colnames(my_raw)<-mylabels
    
    if (tasksubset==1){
      #Now substitute NA for tasks that were not done
      
      mycount<-0
      for (k in 1:myN){
        mycount<-mycount+1
        if(mycount>ncombo){mycount<-1}
        thiscombo<-c(allcombo[,mycount],6+allcombo[,mycount]) #same tests time 1 and 2
        my_raw[k,-thiscombo]<-NA #tests that aren't in thiscombo are assigned to NA
      }
    }
    
    dataRaw      <- mxData( observed=my_raw, type="raw" )
    # #---------------------------------------------------------------------------------------------------------------------------
    #Fully Saturated Model 
    #This acts as baseline: it just models means and variance: no relation between variables, 
    #and no consistency in LI over time
    # -----------------------------------------------------------------------
    
    # residual variances
    resVars      <- mxPath( from=mylabels, arrows=2,
                            free=TRUE, values=rep(1,12), #estimate error variances; same for each test on time 1 and time 2
                            labels=c("e1","e2","e3","e4","e5","e6","e7","e8","e9","e10","e11","e12") )
    # means
    means        <- mxPath( from="one", to=mylabels, arrows=1,
                            free=c(T,T,T,T,T,T,T,T,T,T,T,T), values=c(1,1,1,1,1,1,1,1,1,1,1,1),
                            labels =c("meanA","meanB","meanC",
                                      "meanD","meanE","meanF","meanA2","meanB2","meanC2",
                                      "meanD2","meanE2","meanF2") ) 
    satModel <- mxModel("Saturated model", type="RAM",
                        manifestVars=mylabels,
                        dataRaw, resVars,  means)
    
    mysatFit <- mxRun(satModel) #The mxRun command evaluates the model.
    
    # #---------------------------------------------------------------------------------------------------------------------------
    #Tweak saturated model to check reliability of means
    # means and variances set to be the same for time1 and time2 for each measure
    #This is achieved by giving the path the same name, e.g. meanA for A1 and A2
    # -----------------------------------------------------------------------
    
    # residual variances
    resVars      <- mxPath( from=mylabels, arrows=2,
                            free=TRUE, values=rep(1,12), #estimate error variances; same for each test on time 1 and time 2
                            labels=c("e1","e2","e3","e4","e5","e6","e1","e2","e3","e4","e5","e6") )
    # means
    means        <- mxPath( from="one", to=mylabels, arrows=1,
                            free=c(T,T,T,T,T,T,T,T,T,T,T,T), values=c(1,1,1,1,1,1,1,1,1,1,1,1),
                            labels =c("meanA","meanB","meanC",
                                      "meanD","meanE","meanF","meanA","meanB","meanC",
                                      "meanD","meanE","meanF") ) 
    sat2Model <- mxModel("Reliability model", type="RAM",
                        manifestVars=mylabels,
                        dataRaw, resVars,  means)
    
    mysatFit2 <- mxRun(sat2Model) #The mxRun command evaluates the model.
    reliabtest<-mxCompare(mysatFit,mysatFit2)
    # #---------------------------------------------------------------------------------------------------------------------------
    #Now tweak reliability model to set all means to be the same
    # This tests hypothesis that all measures are similarly lateralised
    # Expect fit to worsen - assuming measures differ in extent of laterality
    # -----------------------------------------------------------------------
    
    # residual variances
    resVars      <- mxPath( from=mylabels, arrows=2,
                            free=TRUE, values=rep(1,12), #estimate error variances; same for each test on time 1 and time 2
                            labels=c("e1","e1","e1","e1","e1","e1","e1","e1","e1","e1","e1","e1") )
    # means
    means        <- mxPath( from="one", to=mylabels, arrows=1,
                            free=c(T,T,T,T,T,T,T,T,T,T,T,T), values=c(1,1,1,1,1,1,1,1,1,1,1,1),
                            labels =c("meanA","meanA","meanA",
                                      "meanA","meanA","meanA","meanA","meanA","meanA",
                                      "meanA","meanA","meanA") ) 
    sat3Model <- mxModel("Equivmeans model", type="RAM",
                         manifestVars=mylabels,
                         dataRaw, resVars,  means)
    
    mysatFit3 <- mxRun(sat3Model) #The mxRun command evaluates the model.
    meanequivtest<-mxCompare(mysatFit2,mysatFit3)
    # #---------------------------------------------------------------------------------------------------------------------------
    #Now tweak meanequiv model to set ABC to be the same and DEF to be the same
    # This tests frontal/posterior difference (which is how data simulated)
    # Expect fit to improve relative to reliab model 
    # -----------------------------------------------------------------------
    
    # residual variances
    resVars      <- mxPath( from=mylabels, arrows=2,
                            free=TRUE, values=rep(1,12), #estimate error variances; same for each test on time 1 and time 2
                            labels=c("e1","e1","e1","e2","e2","e2","e1","e1","e1","e2","e2","e2") )
    # means
    means        <- mxPath( from="one", to=mylabels, arrows=1,
                            free=c(T,T,T,T,T,T,T,T,T,T,T,T), values=c(1,1,1,1,1,1,1,1,1,1,1,1),
                            labels =c("meanA","meanA","meanA",
                                      "meanD","meanD","meanD","meanA","meanA","meanA",
                                      "meanD","meanD","meanD") ) 
    sat4Model <- mxModel("predictedmeans model", type="RAM",
                         manifestVars=mylabels,
                         dataRaw, resVars,  means)
    
    mysatFit4 <- mxRun(sat4Model) #The mxRun command evaluates the model.
   predictedmeanstest<-mxCompare(mysatFit2,mysatFit4)
   #compare with reliability model
    
     #---------------------------------------------------------------------------------------------------------------------------
    # The following models consider covariances
    # Single factor model (means equalized for t1 and t2)
    # -----------------------------------------------------------------------
    
    # residual variances
    resVars      <- mxPath( from=mylabels, arrows=2,
                            free=c(T,T,T,T,T,T,T,T,T,T,T,T), values=c(1,1,1,1,1,1,1,1,1,1,1,1),
                            labels=c("e1","e2","e3","e4","e5","e6","e1","e2","e3","e4","e5","e6") )
    
    # latent variance - Factor1 is the single factor
    latVar       <- mxPath( from="Factor1", arrows=2,
                            free=TRUE, values=1, labels ="varFactor1" )
    # factor loadings
    facLoads     <- mxPath( from="Factor1", to=mylabels, arrows=1,
                            free=c(FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE), 
                            values=c(1,1,1,1,1,1,1,1,1,1,1,1),
                            labels =c("l1","l2","l3","l4","l5","l6","l1","l2","l3","l4","l5","l6") )#same for each test on time 1 and 2
    #The first path is fixed at one - others scaled relative to this
    
    # means
    means        <- mxPath( from="one", to=c(mylabels,'Factor1'), arrows=1,
                            free=c(T,T,T,T,T,T,T,T,T,T,T,T,FALSE), values=c(1,1,1,1,1,1,1,1,1,1,1,1,0),
                            labels =c("meanA","meanB","meanC",
                                      "meanD","meanE","meanF","meanA","meanB","meanC",
                                      "meanD","meanE","meanF",NA) ) #means constant from time 1 to time 2
    
    oneFactorModel <- mxModel("Single Factor Model", type="RAM",
                              manifestVars=mylabels, latentVars="Factor1",
                              dataRaw, resVars, latVar, facLoads, means)
    
    oneFactorFit<-mxRun(oneFactorModel)
    #summary(oneFactorFit) #uncomment this to see results
    
    #---------------------------------------------------------------------------------------------------------------------------
    #Two factor model (means equalized for t1 and t2)
    # -----------------------------------------------------------------------
    
    #two factor model based on:
    #http://openmx.ssri.psu.edu/docs/OpenMx/2.6.7/FactorAnalysis_Path.html#two-factor-model
    
    # latent variances and covariance: NB assume totally independent, so covariance fixed at zero
    latVars      <- mxPath( from=c("Factor1","Factor2"), arrows=2, connect="unique.pairs",
                            free=c(T,T,T), values=c(1,0,1), labels=c("varFactor1","cov","varFactor2") )
    
    
    # factor loadings for Factor1 #NB test A loading is fixed to one for this factor
    facLoadsFactor1     <- mxPath( from="Factor1", to=mylabels, arrows=1,
                                   free=c(FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE), 
                                   values=rep(1,12),
                                   labels =c("k1","k2","k3","k4","k5","k6","k1","k2","k3","k4","k5","k6") )
    
    # factor loadings for Factor2 #NB test A loading is fixed to zero for this factor
    facLoadsFactor2     <- mxPath( from="Factor2", to=mylabels, arrows=1,
                                   free=c(FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE), 
                                   values=c(0,rep(1,5),0,rep(1,5)),
                                   labels =c("l1","l2","l3","l4","l5","l6","l1","l2","l3","l4","l5","l6") )
    
    # means #estimated for all except the two factors
    means        <- mxPath( from="one", to=c(mylabels,'Factor1','Factor2'), arrows=1,
                            free=c(T,T,T,T,T,T,T,T,T,T,T,T,FALSE,FALSE), values=c(1,1,1,1,1,1,1,1,1,1,1,1,0,0),
                            labels =c("meanA","meanB","meanC",
                                      "meanD","meanE","meanF","meanA","meanB","meanC",
                                      "meanD","meanE","meanF",NA,NA) )
    
    twoFactorModel <- mxModel("Two Factor Model", type="RAM",
                              manifestVars=mylabels,
                              latentVars=c("Factor1","Factor2"),
                              dataRaw, resVars, latVars, facLoadsFactor1, facLoadsFactor2, means)
    
    twoFactorFit <- mxRun(twoFactorModel)
    
    factorSat <- mxRefModels(oneFactorFit, run=TRUE)
    factorSatsum<-summary(oneFactorFit, refModels=factorSat)
    factorSat2 <- mxRefModels(twoFactorFit, run=TRUE)
    factorSatsum2<-summary(twoFactorFit, refModels=factorSat2)
    
    #write model likelihoods and dfs to results file
    M1<-summary(mysatFit)
    M2<-summary(oneFactorFit)
    M3<-summary(twoFactorFit)
    myresults[j,1]<-myfactor
    myresults[j,2]<-myN
    myresults[j,3]<-M1$Minus2LogLikelihood
    myresults[j,4]<-M1$degreesOfFreedom
    myresults[j,5]<-M1$BIC.Mx
    myresults[j,6]<-M2$Minus2LogLikelihood
    myresults[j,7]<-M2$degreesOfFreedom
    myresults[j,8]<-M2$BIC.Mx
    myresults[j,9]<-factorSatsum$RMSEA
    myresults[j,10]<-factorSatsum$CFI
    myresults[j,11]<-factorSatsum$TLI
    myresults[j,12]<-M3$Minus2LogLikelihood
    myresults[j,13]<-M3$degreesOfFreedom
    myresults[j,14]<-M3$BIC.Mx
    myresults[j,15]<-factorSatsum2$RMSEA
    myresults[j,16]<-factorSatsum2$CFI
    myresults[j,17]<-factorSatsum2$TLI
    myresults[j,18]<-M2$Minus2LogLikelihood-M3$Minus2LogLikelihood
    myresults[j,19]<-M2$degreesOfFreedom-M3$degreesOfFreedom
    myresults[j,20]<-1-pchisq(myresults[j,12],myresults[j,13])
    
  }
  psummary[myfactor,1]<-myN
  psummary[myfactor,2]<-length(which(myresults[,20]<.05))/nrun
  psummary[myfactor,3]<-length(which(myresults[,20]<.025))/nrun
  psummary[myfactor,4]<-length(which(myresults[,20]<.01))/nrun
#save the summary results
filename<-paste0('Data_from_',myfactor,'factor_N',myN,'_done',donetasks,'_nruns',nrun,'.csv')
write.csv(myresults, filename)
}
psumname<-paste0('psummary_N',myN,'_nruns',nrun,'.csv')
write.csv(psummary,psumname)
#psummary holds proportions where bifactor model is better fit - 
#row 1 has case where data were
#simulated from single factor model (so this is false positive rate)
#and row 2 has case where data were simulated from bifactor model (so this is correct pos rate)


#Uncomment these lines to draw diagram of the models
# omxGraphviz(oneFactorFit, dotFilename="oneFactora")
# grViz("oneFactora")
# 
# omxGraphviz(twoFactorFit, dotFilename="twoFactor.dot")
# grViz("twoFactor.dot")

omxGraphviz(mysatFit,dotFilename='satFactor.dot')
grViz('satFactor.dot')

###new path  diagrams
# library(semPlot)
# semPaths(twoFactorModel,layout="tree2",bifactor="Factor1", residuals = FALSE, exoCov = FALSE,intercepts=F)
# semPaths(oneFactorModel,layout="circle",intercepts=F)


